### PR TITLE
fixed overlapping of nav components

### LINKED ISSUE #98: Overlapping of nav components
Currently there is an overlapping of nav components and banner on the website, which looks like

Screenshot 2024-05-10 at 11 10 56 AM

### PR DESCRIPTION
**Pull request by kartikaysaxena**
Fixes #98 

Screenshot 2024-05-10 at 11 11 26 AM

### CODE REVIEW

**Review by hrishavjha — APPROVED** [review]
Thanks for the fix 🚀

**Review by SahilKr24 — APPROVED** [review]

**Comment by hrishavjha** [comment]
Hey @kartikaysaxena, your commits are not signed. Can you sign all your commis?
Thanks.

**Comment by SahilKr24** [comment]
> Learn more about signing commits.
Hey @kartikaysaxena , what we are looking for is [Learn more about signing commits.](https://docs.github.com/authentication/managing-commit-signature-verification/about-commit-signature-verification).
You can create a gpg key and sign it accordingly. Please let me know if you run into any issues.

**Comment by kartikaysaxena** [comment]
@SahilKr24 @hrishavjha can you please take a look at it now? Thanks!

**Review by SahilKr24 — APPROVED** [review]

**Pull request merged**
