### PR TITLE
Updated the Front End #3751

### PR DESCRIPTION
**Pull request by 0xSaksham**
Changed the required files.

### CODE REVIEW

**Review by avaakash — APPROVED** [review]

**Review by hrishavjha — APPROVED** [review]

**Comment by avaakash** [comment]
Hi @0xSaksham, the DCO is failing can you run the following commands to fix that
1. `git commit --amend --signoff`
2. `git push origin patch-2 --force`

**Comment by 0xSaksham** [comment]
@avaakash I'll do.

**Comment by avaakash** [comment]
@0xSaksham please run the command mentioned above and force push to this branch and PR. We can take the PR after DCO is fixed.

**Comment by 0xSaksham** [comment]
- [ ] @avaakash I'll do today.

**Comment by 0xSaksham** [comment]
@avaakash I have done what you said exactly the same but the DCO error is still there.

**Comment by avaakash** [comment]
Fixes https://github.com/litmuschaos/litmus/issues/3751

**Comment by 0xSaksham** [comment]
Hey, @avaakash is this done?

**Review by ksatchit — APPROVED** [review]

**Comment by hrishavjha** [comment]
Hey @0xSaksham, Can you bring your change into one line, we have our line breaking rules which is causing prettier to fail.
image

**Comment by 0xSaksham** [comment]
@hrishavjha Do I still need to edit it? I guess the PR is closed and Merged.

**Pull request merged**
